### PR TITLE
Removed empty index astro file in and commit message file

### PR DESCRIPTION
**Pull request by skomatireddy**
Removed empty signed off commit file and the index.astro file

### CODE REVIEW

**Review by jminor — APPROVED** [review]

**Review by ee33 — CHANGES_REQUESTED** [review]
Oh I see, STEM2 has its license in-line, whereas the other assets have the license in a separate file.
Can we fix one more thing, while we're in here: Change stem2 page text from "YOU AGREE TO THE TERMS OF THE LICENSE LINKED BELOW" to "YOU AGREE TO THE TERMS OF THIS LICENSE:"

thanks

**Comment by skomatireddy** [comment]
> Oh I see, STEM2 has its license in-line, whereas the other assets have the license in a separate file. Can we fix one more thing, while we're in here: Change stem2 page text from "YOU AGREE TO THE TERMS OF THE LICENSE LINKED BELOW" to "YOU AGREE TO THE TERMS OF THIS LICENSE:"
> 
> thanks

@ee33 I updated the PR to address the above text. The other changes are just due to auto-formatting but shouldn't affect otherwise.

**Comment by ee33** [comment]
Many apologies for leaving this thread for so long -
Srikanth if you are still available, could I ask you to undo the formatting-only changes? I kinda like to keep small diffs small.

**Comment by skomatireddy** [comment]
@ee33 Removed the formatting changes and updated the PR, please take a look, thanks!

**Review by ee33 — APPROVED** [review]

**Pull request merged**
